### ISSUE TITLE
STATUS_STACK_BUFFER_OVERRUN on read_local_base_path()

### ISSUE THREAD

**Issue by puppetmaster-** [rustysec/parselnk-rs#2]
I get the following error when I put the path of my programme's own src folder into this **parselnk::Lnk::try_from()**

_thread 'main' panicked at 'attempt to subtract with overflow', C:\Users\puppetmaster\.cargo\registry\src\github.com-1ecc6299db9ec823\parselnk-0.1.0\src\link_info.rs:195:42
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\/library\std\src\panicking.rs:498
   1: core::panicking::panic_fmt
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\/library\core\src\panicking.rs:107
   2: core::panicking::panic
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\/library\core\src\panicking.rs:48
   3: parselnk::link_info::LinkInfo::read_local_base_path
             at C:\Users\puppetmaster\.cargo\registry\src\github.com-1ecc6299db9ec823\parselnk-0.1.0\src\link_info.rs:195
   4: parselnk::link_info::LinkInfo::new
             at C:\Users\puppetmaster\.cargo\registry\src\github.com-1ecc6299db9ec823\parselnk-0.1.0\src\link_info.rs:154
   5: parselnk::Lnk::new<std::fs::File>
             at C:\Users\puppetmaster\.cargo\registry\src\github.com-1ecc6299db9ec823\parselnk-0.1.0\src\lib.rs:94
   6: parselnk::impl$1::try_from
             at C:\Users\puppetmaster\.cargo\registry\src\github.com-1ecc6299db9ec823\parselnk-0.1.0\src\lib.rs:167_
 
In my opinion, the function should have terminated earlier with an error because it is not an lnk folder at all.
But I don't know enough to see why it didn't do that.

At the moment I have worked around it by checking whether the file has the extension lnk. I wanted to omit working with file extension because the check is error-prone.

Just let me know if I can do anything to help solve the problem.

**Comment by rustysec** [comment]
most definitely... this is a gross bug. i will patch this when i get a minute.

**Comment by puppetmaster-** [comment]
I have now analysed it more closely and first suspected a url file, but it is strangely an rs file. 
![image](https://user-images.githubusercontent.com/10463138/151459030-a9113c39-7b91-4ebb-b7e8-e71dd5e72657.png)

This is what my code looks like that is run through:
```rust
pub fn get_dir_entry(path_buf: &PathBuf, data: &mut AppData) -> Vec<FolderItem> {
    println!("path_buf = {:?}",path_buf);
    let mut list = Vec::new();
    for p in rfm::ls(&path_buf).unwrap() {
        println!("{:?}",p.file_name());
        let mut item = FolderItem::default();
        let mut name = format!("{}",p.file_name().unwrap().to_str().unwrap_or(""));
        let mut size = None;
        let mut locked = false;
        item.hidden = is_hidden(&p);
        //if p.ends_with(".lnk") {
            if let Ok(lnk) = parselnk::Lnk::try_from(p.as_path()){
                if let Some(path) = lnk.relative_path() {
                    let _p = &path_buf.join(path.strip_prefix("./").ok().unwrap()).to_str().unwrap().to_string();
                    let lnk_path = Path::new(_p);
                    name = format!("-> {}",name.replace(".lnk",""));
                    locked = is_locked(&lnk_path);
                    item.path = Arc::new(PathBuf::from(lnk_path));
                    item.lnk = true;
                    if lnk_path.is_file(){
                        size = format_size(&p);
                        item.item_type = Arc::new(ItemType::File);
                    }else {
                        item.item_type = Arc::new(ItemType::Folder);
                    }
                }
            }
.....
 ```

**Comment by rustysec** [comment]
hopefully fixed by c96f60f6a5f80fd51b4044b0fdfd26aba85a6475 in master, let me know if you are still experiencing the issue.

**Comment by puppetmaster-** [comment]
unfortunately no, now it is **read_local_base_path_unicode()**
```
Some("core.rs")
thread 'main' panicked at 'attempt to subtract with overflow', E:\rust_projects\parselnk-rs\src\link_info.rs:230:50
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\/library\std\src\panicking.rs:498
   1: core::panicking::panic_fmt
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\/library\core\src\panicking.rs:107
   2: core::panicking::panic
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40\/library\core\src\panicking.rs:48
   3: parselnk::link_info::LinkInfo::read_local_base_path_unicode
             at E:\rust_projects\parselnk-rs\src\link_info.rs:230
   4: parselnk::link_info::LinkInfo::new
             at E:\rust_projects\parselnk-rs\src\link_info.rs:158
```
if I correct all possible affected locations with the same length query then it works, but I still have the feeling that it should have left the function earlier with an error because it is not an lnk file.

**Comment by rustysec** [comment]
the problem was a little more pervasive, added more validation. thanks for testing!

**Comment by puppetmaster-** [comment]
thanks for the fix ,now everything works as it should, and thanks also for the library is the only one that has all the information i need for my tool
